### ISSUE TITLE
Section 2 - List Structure

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#1]
Version -04

In reading the list in section 2, there is a problem with how the list is presented.  When I read item 1, I expect this to be presented as "1.  Define an asset:"  So that there is a short term followed by an expansion of what that short term means.

As you go down the list, each of the steps gets longer and longer in the first sentence.   Using a short pithy short description followed by a longer description with details is I think a much clearer.  The short description corresponds to the "task" - i.e. a task name.

**Comment by ncamwing** [comment]
Hi Jim,
Hopefully the updates in version -05 should reflect better consistancy as the tasks have been shortened now (followed by longer explanations).

If it is not satisfactory, please feel free to keep this issue opened.

Thanks, Nancy

**Comment by jimsch** [comment]
Version -05

Keeping open on a purely editorial issue.

You need to be consistent on the use of period vs colon at the end of the pity paragraph title.

Otherwise this issue is addressed.

**Comment by jimsch** [comment]
fixed in -07
