### ISSUE TITLE
G-004 Agility

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#10]
Version -04
1.  Standard comment about including the information model in the list of items.
2.  Have we defined the deployment models (and scenarios) so I can check this requirement against the other documents.
3.  By lightweight, do you mean things that do not meet the requirements laid out in this document?

**Comment by jimsch** [comment]
After some discussion with Nancy - I would suggest the following change (addressing item 2)

s/into the different deployment models/into different deployment models/

The use of the definite article here implies that there are specific models that are to be checked as oppose to just the ability to have different deployment models.

**Comment by ncamwing** [comment]
Hi Jim,
Didn't include information model as I see that as something the data model must adhere to so not sure it needs to be included.

I did take your suggestion to address #2 (thanks!)...

"Lightweight" in this instance means to ensure that the code/memory/cpu requirements may be constrained (especially on some endpoints); ergo allowance for such devices to be SACM compliant.

   Nancy.

**Comment by jimsch** [comment]
I would suggest - "including considerations for implementations of data models and transports operating in constrained environments."

**Comment by ncamwing** [comment]
Fair enough....done in -05.

**Comment by jimsch** [comment]
Looks fine to me.
