### ISSUE TITLE
G-006 - Data Integrity

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#13]
Version -04
1.  Where is the data integrity is supposed to be supplied?  Are we just talking about data integrity during transit, are we talking about the ability to do an audit trail to know when and were it was changed, are we talking about end to end integrity?

**Comment by ncamwing** [comment]
Hi Jim,

I am presuming for transport....but I can note it as another discussion point.

   Nancy.

**Comment by llorenzin** [comment]
Addressed at 6/29 virtual interim, done in -07

**Comment by llorenzin** [comment]
Sorry, didn't mean to close this. Addressed at 6/29 virtual interim, done in -07

**Comment by jimsch** [comment]
There has been a change and that change does address my concern, however I am not really happy with the way that it was addressed.

I would prefer to at least some of the text in the security considerations be part of this requirement rather than hiding the security considerations.  I also am reluctant to accept a MUST in the security considerations here.  It is not clear when and how this would be evaluated for somebody comparing a protocol or design against the requirements.

**Comment by llorenzin** [comment]
Fixed in -09 - moved MUST from security considerations into G-006

**Comment by jimsch** [comment]
wfm
