### ISSUE TITLE
G-007 - Data Isolation.

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#14]
Version -04

This item appears to be two different things that are reasonable, jammed together into a single requirement.

G-007  Data Partitioning:  A method for partitioning data MUST be supported to accommodate considerations such as geographic, regulatory, operational requirements, overlay boundaries and federation where the data may be collected in multiple locations and either centralized or kept in the local region.  Where replication of data is supported, it is required that methods exist to prevent update loops.

G-007A Data Access Control:  Methods of access control MUST be supported to accommodate considerations such as geographic, regulatory, operational and federations.  Entities accessing or publishing data MUST identify themselves and pass access policy.

**Comment by ncamwing** [comment]
Hi Jim,
I like your clarifications better so will incorporate them as 2 separate requirements in replacement to G-007.

Thanks, Nancy.

**Comment by jimsch** [comment]
Looks fine to me.
