### ISSUE TITLE
G-008 - Versioning and Backward Compatability

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#15]
Version -04

I don't believe that this is a requirement that you want to have.  I don't believe that this makes sense.  What you want would appear to just be a capability discovery mechanism.  What a version means would be very unclear if you had a mixed of standard and non-standard mechanisms and capabilities installed.  Each of the items to be discovered would need to have independent version numbers.  It is not clear that if a new mechanism is published that it would need to be backwards compatible with an old, but similar, mechanism. Instead both mechanisms would be published independently.

**Comment by ncamwing** [comment]
Hi Jim,

But a capability could be versioned as well?  That is, a capability of version 1 could be to support two data models, but in the next version you add a third.  So, it is still the same capability but allowed using more data models....perhaps I'm thinking along the lines of how a couple of different pub-sub mechanisms work....

   Nancy.

**Comment by jimsch** [comment]
I guess keep it.  It will be interesting to see what people do to try and deal with this.

**Comment by jimsch** [comment]
I am not sure what people are going to do to implement or understand this requirement, but Nancy seems to know what it is supposed to do.

**Comment by ncamwing** [comment]
Hi Jim,
Once we have proposals coming in, perhaps we can demonstrate it through applicability?  But this is something I'm seeing as needed as different data models (and versions within data models) are being supported in different messaging systems....
