### ISSUE TITLE
G-010 - Endpoint Discovery

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#16]
Version -04

I don't understand why this is not a sub case of requirement G-009.   From the text is not clear that there is a reason to call this out separately.

**Comment by ncamwing** [comment]
Hi Jim,
Mainly because of my laziness.....but in reality, I think the group wanted to have an explicit requirement for endpoint discovery....I'll note it for wider discussion.

```
Nancy.
```

**Comment by llorenzin** [comment]
G-009 refers to information in the ecosystem - data (objects).  G-010 refers to endpoints in the ecosystem - components (subjects).  Does that help make it clear why these are separate requirements?

**Comment by jimsch** [comment]
By the information in the ecosystem do you mean discovering the schema or discovering the individual pieces of data?

**Comment by ncamwing** [comment]
My interpretation is G-009 speaks to the available schemas/data models whereas as G-010 are the actual SACM endpoints in the ecosystem that can provide individual pieces of data.

**Comment by llorenzin** [comment]
Discussed at 6/29 virtual interim, done in -07
