### ISSUE TITLE
G-011 - Unsolicited publication, updates,...

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#17]
Version -04

Push and Pull Access:  There MUST be support for three methods of data access.  The standard Pull model as well as solicited and unsolicited Push models.  All of the methods of data access must support the ability for the initiator to filter the set of posture assessment information to be delivered.  Additionally, the provider of the information needs to filter the set of posture assessment information based on the permissions of the recipient.  This requirement is driven by use cases 2.1.3, 2.1.4 and 2.1.5.

What you currently have is unclear and messy.  
- It does not have a pithy title
- The "title" that is there does not correspond to all of the content of the paragraph.  TItle is unsolicited, but there is a sentence for solicited  and pull as well.

**Comment by ncamwing** [comment]
Hi Jim,

Yes, the bullet has been well mangled because as a group we have switched between publisher, provider and push( model).  Do you have suggestions on a better requirement? (I hazard to take another pass as I've already taken several and not gotten it crisp)

Thanks, Nancy

**Comment by jimsch** [comment]
Do you want to comment on what is in the original message in terms of what you feel is missing?

**Comment by llorenzin** [comment]
I like this replacement text for G-011 very much!  Only change i would make is to make the normative requirements clear:

Push and Pull Access: Three methods of data access MUST be supported: the standard Pull model as well as solicited and unsolicited Push models. All of the methods of data access MUST support the ability for the initiator to filter the set of posture assessment information to be delivered. Additionally, the provider of the information MUST be able to filter the set of posture assessment information based on the permissions of the recipient. This requirement is driven by use cases 2.1.3, 2.1.4 and 2.1.5.

**Comment by ncamwing** [comment]
Thanks for this text Lisa, I like it much better.  Will be updated in -05.

Jim: hopefully this makes it more clear?

Thanks, Nancy

**Comment by jimsch** [comment]
No problems with Lisa's text.

**Comment by jimsch** [comment]
Looks fine to me.
