### ISSUE TITLE
G-013 - Device Location

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#18]
Version -04

A SHOULD worries me.  Are you saying that this SHOULD be support or that it MUST be supported and SHOULD be available.  Are you willing to accept a solution which does not meet this requirement?

**Comment by ncamwing** [comment]
Hi Jim,
I think that it is meant to be of the target endpoint not the SACM component "endpoint"....given that, it probably should be a MUST for both and I'll also clarify that it is the target endpoint.

Thanks for catching this,
    Nancy.

**Comment by jimsch** [comment]
Looks fine to me.
