### ISSUE TITLE
Section 2. - Task "define the assets"

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#2]
Version -04
1.  Recommend starting with "Define an asset:"  The task is simpler if you think of doing it for one thing that for every thing.
2.  I have a problem with the term define an asset in general.  This is really talking about defining the properties or attributes of an asset.   The attributes are the things that we want to know about the asset.
3.  The current text does not make it clear that things other than software are assets.  It would be good to add a list of different types of "asset classes."  On this list would be endpoints and software at a minimum.  It might be worth while to breakout end points as a separate definition step so that we know what they are by the time we get to the current step 2 in the list.
4.  If software is an asset, then talking about it being installed does not make sense.  "For instance, a software package can be defined as an asset.  Examples of properties of the software package would include, what the version of the package is, what patches have been applied to the package, what software assets that this package depend on are installed (along with their attributes)"

**Comment by ncamwing** [comment]
Hi Jim,

I really think the assets are defined as attributes in the information model. So perhaps we need to assert that, but its probably best to take it up to the group for discussion?

```
Nancy.
```

**Comment by jimsch** [comment]
I have not see this as a group discussion yet.  Perhaps it is a new issue?

**Comment by llorenzin** [comment]
Fixed in -08

**Comment by jimsch** [comment]
wfm
