### ISSUE TITLE
G-012 - Device Interface

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#20]
Version -04
1.  This requirement uses the term endpoint twice.  According to how I understand this requirement, there are two different ways that the term endpoint can be interpreted and the two uses have different interpretations in this case.  I think the first instance includes all providers and customers, while the second endpoint is only target endpoints.   If I am correct then there needs to be a distinction between the statements.  
2.  s/which endpoint communicate/which endpoints communicate/

**Comment by ncamwing** [comment]
Hi Jim,

You are right!  I will update it to read:
Device Interface: the interfaces by which SACM components communicate to share endpoint posture information MUST be well defined.

OK?
- Nancy

**Comment by jimsch** [comment]
That looks fine.

**Comment by jimsch** [comment]
Looks fine to me.
