### ISSUE TITLE
ARCH-005: Modularity

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#22]
Version -04

This requirement appears to be a duplicate of requirement G-005 and G-008.  What is the reason for having this be distinct?

**Comment by ncamwing** [comment]
Hi Jim,
I view versioning and back compabilitibility as being somewhat different than extensibility.
The extensibility is to allow for other (especially vendor specific) attributes to be allowed (but not mandatory to SACM)....

```
Nancy.
```

**Comment by llorenzin** [comment]
Nancy, I read what Jim is saying as - extensibility (G-005) and versioning / backward compatibility (G-008) are already defined as general requirements, so why have the same requirement again in the architecture section?  Jim - i think the answer is: ARCH-005 is specific to how the components are expected to interact with each other, which is defined in the architecture.

**Comment by jimsch** [comment]
No change needed.  Lisa is correct in terms of what I was asking.
