### ISSUE TITLE
ARCH-007: Context-based Authorization

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#23]
Version -04
1.  The more common phrase for what I think you are trying to state here is "Attribute Based Authorization".  The term context based could be implied to say something along the lines of - release this piece of data only when that piece of data is also being requested.  However, I believe what you are really looking at here is that you want to say - Only release the data if the requester has specific attributes.

While this usage could subsume ARCH-006 as well (a role being an attribute), it is reasonable to keep them both as people tend to think of role based authorization as a normal method of granting access to something.
1.  I have a problem with the second sentence when one is discussing what consumers can expose and share.  While it is true that policy does include this information, there is nothing that can be done in the architecture to enforce this.  A different, but enforceable, requirement on customers would be that they must act as providers and do the appropriate policy enforcement before passing data on to another endpoint.

**Comment by ncamwing** [comment]
Hi Jim,

I'm OK changing it to "attribute based" vs. "context based".....but the intent was to allow for a "group of attributes" (ergo context) as well; so my concern with the change is that readers might infer it to be single attribute only?

As to the 2nd sentence, you are right.  But the intent of this requirement is to ensure that authorization is done at the management layer, whether it be by the "management module" that is hosted by either a server or local to the endpoint (that is consuming or providing).  So, I agree that from a standards perspective we can not enforce it, but like the EAP framework and such, there has to be some mention of this requirement to ensure appropriate security.

   Nancy.

**Comment by jimsch** [comment]
One way to fix your worry might be to change the second sentence as follows:

Different policies (e.g. business, regulatory, etc.) may specified what data may be exposed to, or shared by consumers based on one or more attributes of the consumer.  The policy may specify that consumers are required to share specific information either back to the the system or to administrators.

**Comment by ncamwing** [comment]
I like that better, will incorporate into -05

**Comment by jimsch** [comment]
Looks fine to me.
