### ISSUE TITLE
IM-002: Ephemerality

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#25]
Version -04
1.  s/by a requestor/by an endpoint/   requestors do not provide information.
2.  I don't understand what this requirement is trying to say.  It needs to be expanded.  
3.  when can the SHOULD be violated - is it a killer for an IM?

**Comment by ncamwing** [comment]
Updated "requestor" to "endpoint".

The requirement is really trying to state that a data model SHOULD support at least one but can support both solicited and unsolicited requests (e.g. query and/or pub-sub).

How about if we updated it to read:
"Posture Data requests: The Information Model SHOULD account for the Posture information's ephemerality as the data may be provided by an endpoint either solicited or unsolicited. That is, data models MUST support at least one or both means to request data: solicited or unsolicited."

That way, we don't have to clarify "ephemerality" either ...
  Nancy

**Comment by llorenzin** [comment]
The endpoint generates the data, but is not necessarily (and probably won't be, in most cases) the component publishing the information. The provider is the component publishing the information.  Further, this requirement refers not to a means to _request_ data (requested data is by definition solicited), but a means to _publish_ data.  So I'd revise to:

"Posture Data Publication: The Information Model SHOULD account for the Posture information's ephemerality as the data may be provided by an endpoint either solicited or unsolicited. That is, data models MUST support at least one or both means to publish data: solicited or unsolicited. For example, a compliance-server provider may publish endpoint posture information in response to a request from a consumer (solicited), or it may publish posture information driven by a change in the posture of the endpoint (unsolicited)."

**Comment by jimsch** [comment]
I find the update from llorenzin to be clearer in terms of what is being required.  I am still not sure what the word 'ephemerality' is supposed to mean here, but pulling it out of the pithy title means I don't care as much.

**Comment by ncamwing** [comment]
So, I think the first sentence is not clear....and yes, I had to look up the definition of "ephemeral" to see if we were using it correctly and I believe we are not:

From http://www.merriam-webster.com/dictionary/ephemeral:
adjective ephem·er·al \i-ˈfem-rəl, -ˈfēm-; -ˈfe-mə-, -ˈfē-\
1
:  lasting one day only <an ephemeral fever>
2
:  lasting a very short time <ephemeral pleasures>

Which is NOT the intent of requirement; I believe the requirement is about ensuring the Information Model allow for the information to be acquired solicted or unsolicited.  So, another suggested update:

"Posture Data Publication: The Information Model SHOULD allow for the data to be provided by an endpoint either solicited or unsolicited. That is, data models MUST support at least one or both means to publish data: solicited or unsolicited. For example, a compliance-server provider may publish endpoint posture information in response to a request from a consumer (solicited), or it may publish posture information driven by a change in the posture of the endpoint (unsolicited)."

**Comment by jimsch** [comment]
Looks fine in -05.
