### ISSUE TITLE
IM-003  Data model negotiation

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#26]
Version -04

Why should an IM care about this?  It makes more sense that this would be an architectural requirement along the lines of:

ARCH-????:  Data model negotiation:  SACM's Architecture MUST allow for the support of multiple data models for any given Information Model.  There MUST be support for a consumer to determine what Data Models exist within a deployment that support a given Information Model.

**Comment by ncamwing** [comment]
Hi Jim,
Ah, I think I distinguish the definitions of the interfaces that allow the "components" in the architecture to be part of the information model requirements.  That is, "architecture" describes the functional components and the responsibilities of the components but how they interface to be part of the information model.
Given that definition, I'm not sure I would put it in architecture but leave it as part of the info model....

Again, believing that SACM defines one single "SACM information model"....

Nancy.

**Comment by llorenzin** [comment]
I fall with Nancy on this one, fwiw. High-level roles and capabilities of the components goes in architecture, operations goes in information model, and this is a requirement against the operations.

**Comment by jimsch** [comment]
My problem with this is that if it is a requirement on the IM.  I have a tendency to consider it to be an attribute that must be defined in the IM that can then be queried.  Putting into the architecture makes me think of it in terms of an operation that can be done independent of IMs and DMs.

**Comment by ncamwing** [comment]
Hmmm....so I think it may be needed for both the interfaces and the data structures?  e.g. IM and operations of data model?

**Comment by jimsch** [comment]
That would probably be clearer.

**Comment by ncamwing** [comment]
I've updated the IM-003 sentence to read:
 SACM's Information Model MUST allow support for different data models, data model versions and different versions of the operations (and network layer transport).

in -05....

**Comment by jimsch** [comment]
Version -05
The last sentence is missing some words in it.  /of a particular or/of a particular data model or/

**Comment by ncamwing** [comment]
Updated in -06.

**Comment by jimsch** [comment]
Fixed in -06
