### ISSUE TITLE
DM-003: <No pity title>

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#28]
Version -04

I have not come across the term "rootless search" before.  A definition would be useful.

**Comment by jimsch** [comment]
Should potentially combine DM-003 and DM-004 into a single requirement.

**Comment by ncamwing** [comment]
Hi Jim,
I think "rootless" meant to imply that the data models need not follow a specific database pattern...in reading DM-003 and DM-004 are very similar....but I'm having trouble coming up with language to help clarify and merge. 

Any suggestions?

Thanks, Nancy

**Comment by llorenzin** [comment]
I agree that DM-003 and DM-004 should be merged.  Suggestion:

DM-00x: Search Flexibility: The search interfaces and actions MUST include the ability to start a search anywhere within a data model structure, and the ability to search based on patterns ("wildcard searches") as well as specific data elements.

**Comment by jimsch** [comment]
That makes a clear requirement.

**Comment by ncamwing** [comment]
will incorporate in -05

**Comment by jimsch** [comment]
Looks fine in -05.
