### ISSUE TITLE
DM-005:  <data lifetime management>

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#29]
Version -04
1.  Add a pity title - suggest the test in the header for this issue
2.  I believe that part of this should be moved to an IM requirement.  the IM should talk about longevity of data.  This would be in terms of specifying maximum and minimum requirements that a DM would need to deal with.  I would not necessarily expect that different DMs should handle the question of when data expires significantly differently.

**Comment by ncamwing** [comment]
Hi Jim,

Title added as you suggested in your #1.
As to #2, I will add a new IM requirement (and agree that data expiry is subjective, but I was asked to add it in the text?):
IM-005 Data lifetime management: The information model MUST provide a means to allow data models to include data lifetime management. The information model must identify attributes that can allow data models to at minimum, identify the data's origination timestamp and potential expiration or lifetime (that the data may be expected to be valid).

Thanks, Nancy

**Comment by jimsch** [comment]
Looks basically good suggest

s/timestamp/time/ - timestamps tend to have a specific meaning to me and I am not sure that is what you intend here.
s/potential expiration or lifetime (that the data may expected to be valid)/ expected time of next update or data longevity (how long should the data be assumed to still be valid)/

**Comment by ncamwing** [comment]
Done in -05!

**Comment by jimsch** [comment]
Looks good in -05
