### ISSUE TITLE
Section 2 - "assets and endpoints"

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#3]
Version -04
1.  Should this task be divided into two different tasks.  The first is to determine if an asset should be associated with an "endpoint class".  (The specific end point being a member of that class.)   The second would be the actual endpoint assessment operation.
2.  Use the correct term from the terminology document about what this task is.  I believe that the task this item is describing is "Assessment".  I would recommend that the task be named "Endpoint Assessment" even though the term is redundant.
3.  What is the difference between "data elements" and "attributes"?  In both cases the terms should have been defined in some sense in the preceding tasks.  I.e. when did we create either that attributes and/or the data elements in the tasks?
4.  Are we exchanging or publishing information in this step?  Is this step going to include the concept of an attribute of  an asset including the result of an evaluation or not?  If so then this type of thing needs to be included in the description somehow.

**Comment by ncamwing** [comment]
Hi Jim,

Pragmatically, I would think there would be a (guidance) template that would already have defined the relevant assets for an endpoint class.  So perhaps I can break it as you suggest to "Map the assets associated with an endpoint class"....

I'm not sure I understand the last part of #3....the attributes are defined in the terminology and should be  also in the information model.
There is no difference between "data elements" and attributes....so I can remove "data elements"

This "task" could exchange or publish information as part of the "creation" of such a template, though I think in cases I know today, they are constructed manually.

   Nancy.

**Comment by jimsch** [comment]
Removal of data elements makes the term attributes self evident.

**Comment by ncamwing** [comment]
Agreed....the text has been updated to remove "data elements"

**Comment by jimsch** [comment]
This item is still missing the step of collecting the assets as a separate item.  It should probably be there.

Did you really mean to remove the "Define the assets" step from this?

**Comment by llorenzin** [comment]
Fixed in -08

**Comment by jimsch** [comment]
wfm
