### ISSUE TITLE
DM-012: Attribute Dictionary

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#32]
Version -04
1.  Much of this requirement seems to be more closely associated with the IM than the DM.  If the IM is not clear about what the meaning of attributes are, then the DM with either need to make a decision about what it means (which means that two different DMs could decide differently) or the requirement is not enforceable.
2.  I can understand a DM having attribute collection, but I thought that aggregation was placed in a customer/provider role and not part of the DM itself.  
3.  How much of this requirement is subsumed by IM-001?

**Comment by ncamwing** [comment]
Hi Jim,
MOST of it is subsumed by IM-001.  However, IM-001 defines the MUST attributes to be defined in SACM (along with extensibility).  However, data models may extend their attributed dictionary to include other attributes (as extensions to SACM's IM)....

I personally can go either way; e.g. remove it as it is really part of the Info Model's purview to ensure the intent and semantics are well understood for SACM....the extensions specific to the data model not so much in scope for us?

Is this one to take to the group for consensus?

Thanks, Nancy

**Comment by jimsch** [comment]
I think it makes sense to have a requirement that a DM can define additional attributes which are not part of the IM and there are clarity requirements on these new attributes.

I never have problems with group discussion on any issue.

**Comment by ncamwing** [comment]
Hi Jim,
Once I can crank the -05 and submit, my plan was to summarize all the issues we need to discuss, this is one of them.

Thanks, Nancy

**Comment by llorenzin** [comment]
I like Jim's suggestion here, that a DM can define additional attributes which are not part of the IM and there are clarity requirements on these new attributes.

**Comment by ncamwing** [comment]
I am not sure how we can enforce such a requirement as they will not really be part of the SACM "MUST" list?

**Comment by llorenzin** [comment]
Discussed at 6/29 virtual interim, done in -07
