### ISSUE TITLE
DM-013:  Transport Agnostic

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#33]
Version -04

I completely agree that this is not a DM requirement but should be in the  transport section.  This requirement has nothing to do with the representation of data, or even how the data is queried.  It is strictly a transport question.

**Comment by ncamwing** [comment]
Thanks Jim.....I will move it to the transport section.
- Nancy

**Comment by jimsch** [comment]
Looks fine in -05.
