### ISSUE TITLE
DM-016: Data Source Location

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#35]
Version -04

The meaning of this requirement is not clear to me.  It could be represent two different things and needs to be clarified
1.  The physical or logical location of the entity that provides the data
2.  The location where the data was stored when it was provided to the customer.

**Comment by ncamwing** [comment]
Hi Jim,
This is a fair point.  I think the location is really meant to be a "source" of the data not really the physical (geographical or topological) location of the data provider.  We haven't really tagged or defined what a "source" would be, I think this could be a hostname, domain (DNS) name or application name.

Would you accept a rewording to be:
The data model SHOULD allow the provider to include attributes defining the data source (e.g. hostname, domain (DNS) name or application name.)

Thanks, Nancy.

**Comment by jimsch** [comment]
Perfectly reasonable update.  I wonder if you would also like to include “collector” to the list of possible data sources or do you think that is covered by application name?

Jim

**Comment by ncamwing** [comment]
Yes, actually “application” could be a collector, aggregator, producer, or any other type of application that could be storing relevant posture information.

Thanks, Nancy

**Comment by jimsch** [comment]
I think this is probably ok in -05.
