### ISSUE TITLE
Section 2.6 - Requirements for Transport Protocols

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#36]
The term Transport Protocol is extremely ambiguous in this section.  It has at least two different meanings that can be used in this section and both of them do, at times, seem to be used.

The first is that of Transport Layer Protocols, such as TCP, IP, UDP, Bluetooth and so forth.
The second is that of a SACM Data Transport Protocol (sorry I can't list any at this point).
There is a third set that can be considered to be in this category that don't fall into either of these in some sense (i.e. TLS, DTLS, RSYNC).

I strongly recommend that distinct terms be defined for each of these be created, their existence documented (either here or in terminology) and then be used consistently.

**Comment by ncamwing** [comment]
Hi Jim,

My intent was to have this section refer to the network transport layer protocols....the data transport I thought and labeled as "operations on the data model"....does that make sense?

but I will note this in the draft for us to discuss in the wider group (and if I remember, to bring it back to the sacm group mailer)...

Thanks, Nancy

**Comment by llorenzin** [comment]
Discussed at 6/29 virtual interim, done in -07

**Comment by jimsch** [comment]
It would still be useful to have an intro paragraph that discusses the two terms that are used and how they are distinct.

**Comment by llorenzin** [comment]
Please propose text here and we will incorporate.

**Comment by jimsch** [comment]
The term transport protocol is frequently overloaded.  The term SACM transport protocol is intended to be distinguished from underlying layer 3 and 4 protocols such as TCP/IP and TLS.  However, it is possible that a layer 3 or 4 protocol may be used as a SACM transport protocol either alone or as part of a SACM transport protocol (i.e. using HTTP over TLS with XML as the content).  The SACM transport protocol is focused on moving data and performing necessary access control operations, it is not focused on performing operations on SACM components.

**Comment by sacm** [comment]
On Wed, Jul 22, 2015 at 12:35 PM, Jim Schaad notifications@github.com
wrote:

> The term transport protocol is frequently overloaded. The term SACM
> transport protocol is intended to be distinguished from underlying layer 3
> and 4 protocols such as TCP/IP and TLS. However, it is possible that a
> layer 3 or 4 protocol may be used as a SACM transport protocol either alone
> or as part of a SACM transport protocol (i.e. using HTTP over TLS with XML
> as the content). The SACM transport protocol is focused on moving data and
> performing necessary access control operations, it is not focused on
> performing operations on SACM components.
> 
> Wouldn't "transfer protocol" be more appropriate?

Thanks,
Kathleen

> —
> Reply to this email directly or view it on GitHub
> https://github.com/sacmwg/draft-ietf-sacm-requirements/issues/36#issuecomment-123782748
> .
> 
> ---
> 
> sacm mailing list
> sacm@ietf.org
> https://www.ietf.org/mailman/listinfo/sacm

## 

Best regards,
Kathleen

**Comment by adammontville** [comment]
Are we making this too difficult?  The semantics of _transport_ change with context, and that context is really about which layer we're talking about. I think the text Jim has provided is sufficient, and thank him for the contribution.  I don't think changing from _transport_ to _transfer_ is necessary.

**Comment by llorenzin** [comment]
Revised to:

The term transport protocol is frequently overloaded. The term SACM transport protocol is intended to be distinguished from underlying layer 3 and 4 protocols such as TCP/IP and TLS. However, it is possible that a layer 3 or 4 protocol may be used as a SACM transport protocol either alone or as part of a SACM transport protocol (i.e. using HTTP over TLS with XML as the content). The SACM transport protocol is focused on moving data and performing necessary access control operations; it is agnostic to the data model operations.

**Comment by llorenzin** [comment]
Fixed in -09 - text added.

**Comment by jimsch** [comment]
wfm
