### ISSUE TITLE
T-001 - Transport variablity

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#37]
Version -04
1.  The text is not clear in terms of what is meant by the use of transports in this requirement.  Not even the pithy title is clear on this.

What I think you are trying to say:

T-001 Multiple Data Transport Protocol Support:  Different Data Transport Protocols MUST be supported in a deployment to support different transport layer requirements, different device capabilities and system configurations dealing with connectivity.

T-XXX  Transport Layer Requirements:  Each Data Transport Protocols MUST clearly specify the Transport Layer requirements it needs to operate correctly.  Examples of items that may need to be specified include connectivity requirements, replay requirements, data link encryption requirements, channel binding requirements.  These requirements are needed in order for deployments to be done correctly.  For example, a proxy server between UDP and TCP can provide a connection that correctly fulfills the connectivity and replay requirements as well as data link requirements (through the use of TLS and DTLS) but would be unable to provide a channel binding requirement as that implies there is no MITM to look at the data.

**Comment by llorenzin** [comment]
Discussed at 6/29 virtual interim, done in -07
