### ISSUE TITLE
DM-001 - no pity title

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#38]
Version -05

DM-001  Uniqueness: The data model MUST associate each data object with exactly one information model element.

saying they are objects imposes an implementation requirement on the DM.
In re-reading this requirement, I got confused in terms of what it means.  The above is my best guess as to what it was intending.

**Comment by ncamwing** [comment]
Yes, I believe that is the intent, so will clarify accordingly.

Thanks, Nancy

**Comment by llorenzin** [comment]
Fixed in -08 - reworded to clarify intent.

**Comment by jimsch** [comment]
wfm
