### ISSUE TITLE
OP-004 Attribute based query

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#42]
Version -05
I think that a requirement similar to OP-002 needs to be part of the query language as well.   That is the query needs to be constructed rather than directly executed from the request.

**Comment by ncamwing** [comment]
Hmmm.....isn't that what OP-002 is intended for? or do you mean construct a query operation based on OP-002 (e.g. the collection guidance)?

**Comment by jimsch** [comment]
After reading the requirement multiple times,  I ended up believing that OP-002 referred to the operations where a bac-kend was asking a collector for attributes about somebody.  This seemed to be more a client asking the back-end about things.  While the architecture seems at time to conflate these concepts, it is not done uniformly.

**Comment by llorenzin** [comment]
Discussed at 6/29 virtual interim, done in -07
