### ISSUE TITLE
OP-006 Data model scalability

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#43]
Version -05

This is a data model requirement as stated.  It needs to be transformed into an operations statement.

is this a requirement that a query operation can return a large amount of data and the operation needs to support this?

**Comment by ncamwing** [comment]
Correct, the query operation MUST handle large amounts of data, and the mechanism must also account for the ability of having many sources that can provide the data.  How about:

The operation resulting from a query operation MUST be able to handle the return and receipt of large amounts of data.  Use Cases 2.1.4 and 2.1.5 describes the need for the data model to support scalability. For example, the query operation may result in a very large set of attributes, as well as a large set of targets.

**Comment by jimsch** [comment]
Looks fine.

**Comment by jimsch** [comment]
done in -06
