### ISSUE TITLE
OP-XXX Component identification

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#44]
OP-XXX Component Identification:  Data Model interfaces MUST have clearly identified identification of the components at each end.  Authorization decisions are based the ability to identify and validate the entity at the other end of the interface, the interface therefore needs to clearly identify who is at the opposite end as well as provide the ability to provide proof of identity.

**Comment by jimsch** [comment]
Looking at the T-XXX requirements.  I believe that most of them should be moved to OP-XXX requirements.  Many/most of them would not be supportable by a transport internet layer.

**Comment by ncamwing** [comment]
But if we use TCP as a transport then we should be enforcing some level of security (e.g. TLS with security enabled not just null crypto).  So I think they do need to be part of the transport.
Question is to whether we need to impose it as operations on the data model too?

**Comment by jimsch** [comment]
The security requirements could be met in at the OP layer rather than at the T layer

**Comment by llorenzin** [comment]
Discussed at 6/29 virtual interim, done in -07

**Comment by jimsch** [comment]
I don't recognize any changes to address this issue.

**Comment by llorenzin** [comment]
Sorry, Jim, I caught the part about distinguishing between operations and transport requirements but missed the part on walking through these to see if they need to be moved. That latter part still needs to be done.

**Comment by llorenzin** [comment]
Fixed in -08

**Comment by llorenzin** [comment]
Fixed in -08 - section now titled SACM transport protocols for clarity

**Comment by jimsch** [comment]
waiting on #36 but expect it to be fine

**Comment by llorenzin** [comment]
#36 is done in -09

**Comment by jimsch** [comment]
wfm
