### ISSUE TITLE
ARCH-005: Modularity

### ISSUE THREAD

**Issue by henkbirkholz** [sacmwg/draft-ietf-sacm-requirements#47]
ARCH-005: "Announcement and negotiation of functional capabilities (such as authentication protocols, authorization schemes, data models, transport protocols, etc.) must be supported, enabling a SACM component to make inquiries about the capabilities of other components in the SACM ecosystem."

This requirement seems to merge multiple quite generic concepts. This could be phrased more precise or could be broken up into multiple, more specific items?
There is no definition of Modularity, at the moment. Modularity seems to imply the use of Building Blocks ("what is the subject to modularity"). There is actually a definition of Building Blocks  in terminology draft, but that definition is even more generic (at the moment) and does not seem to align very well with this requirement.

In this requirement, is the term Modularity targeting the interconnectedness/interoperability of SACM data model and SACM transport drafts?

If the scope of this requirement encompasses concepts, such as Data Plane Content (Type) Negotiation, Management Plane Feature Negotiation, or Publishing of (and subscribing to) Feature Lists maybe the title could be something like "Negotiation (of Content & Features)"?

In any case, the term "functional capabilities" should be rephrased or dropped via restructuring, as indicated in Issue https://github.com/sacmwg/draft-ietf-sacm-terminology/issues/8 ("Capability and Function").

**Comment by llorenzin** [comment]
Resolution: change title from Modularity to Capability Negotiation

**Comment by llorenzin** [comment]
Fixed in -09
