### ISSUE TITLE
DM-001 - terminology / data object

### ISSUE THREAD

**Issue by llorenzin** [sacmwg/draft-ietf-sacm-requirements#48]
DM-001 is the only place we refer to a "data object".  It's not clear to me what this term means in this context.  If it means "attribute" we should just say so. If it includes data beyond attributes, we need to a) agree on what it means, and b) add "data object" as an entry in the terminology draft.

**Comment by henkbirkholz** [comment]
It is not clear to me either, I think.

It could be any of these (or any combination of these):
- attribute
- attribute value pair
- endpoint attribute
- endpoint attribute assertion
- posture attribute
- ...

Maybe, a better understanding and definition of the basic elements SACM is processing (and how they could be composed into larger structures) will clarify this.

**Comment by llorenzin** [comment]
fixed in -08 - changed to "data object" to "data model element"
