### ISSUE TITLE
DM-001 - association of data objects

### ISSUE THREAD

**Issue by llorenzin** [sacmwg/draft-ietf-sacm-requirements#49]
The draft currently states that that a data object should be associated with exactly one information model element - endpoint, IP address, asset, etc.  Why?  An IP address is not the same class of element as an endpoint; an IP address is one identifying aspect of an endpoint. So an attribute could be applicable to both an IP address and to the endpoint on which that IP address is configured. If the attribute collector is aware of the relationship between the IP address and the endpoint, are we saying that it must only publish the attribute on one or the other, but not both?  This seems problematic.

**Comment by jimsch** [comment]
This is the same as issue #38

**Comment by llorenzin** [comment]
Fixed in -08 - clarified that the data model must include elements for each element in the information model, and may also include additional elements.
