### ISSUE TITLE
IM-002 / DM-016 change normative language to MUST for consistency

### ISSUE THREAD

**Issue by llorenzin** [sacmwg/draft-ietf-sacm-requirements#51]
Requirement G-011 states that pull, push/solicited, and push/unsolicited data access methods MUST be supported. IM-002 and DM-016 say that the information model and data model SHOULD allow for / enable a provider to publish solicited or unsolicited information. I believe the latter need to upgraded to MUST for consistency with G-011 and to ensure the intended functionality is supported.

**Comment by jimsch** [comment]
Looking at this, I don't know what it would mean for an IM to support either push or pull.  I think that this are going to be requirements on the DM and OP rather than on the IM.  However I agree that the requirement needs to be upgraded.

**Comment by llorenzin** [comment]
Done in -07
