### ISSUE TITLE
Do we need a privacy section

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#55]
version -09

This is just a question.  The response may be that no change is needed.

Do we need to have a separate privacy question to highlight anything about both general privacy and pervasive monitoring.  This system is, in some respects, a pervasive monitoring system and we might need to highlight this.

**Comment by sacm** [comment]
Hi,

My two cents - yes - pervasive monitoring is a legal and social concern of
the first importance - the current SACM Requirements spec is very light on
privacy requirements in main body and privacy discussion in the Security
Considerations section.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Winter  579 Park Place  Saline, MI  48176  734-944-0094
Summer  PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by adammontville** [comment]
I agree that privacy needs to be covered.  

Still, when we talk about _identity_ or _identification_ in this working group, we're talking about something different than PII data.  As such, there's this other issue for the information model https://github.com/sacmwg/draft-ietf-sacm-information-model/issues/21, which is seeking to get feedback on what a useful term other than identity might be.  The present candidate seems to be _designate_.  So, instead of "identify an endpoint" we would "designate an endpoint" or "collect AVPs from the designated set of endpoints".  

I also wouldn't go so far as to say that we're performing pervasive monitoring in the sense that mainstream media understands the term.  Our scope has always been single-enterprise, and it remains that way.

Again, privacy is important, but I don't think we're talking about PII as much as might be implied by our choice of terms.

**Comment by sacm** [comment]
My understanding on PII is that as soon as I associate a person with an 
email address, phone number or physical address I have PII that I need 
to protect. If we associate a user id, account or user provisioned PKI 
with a device including possibly a MAC address we probably have the same 
concerns.

I think in many cases user certificates are used for device 
authentication and I thought that was an attribute that was highly 
desirable.

On 8/7/15 7:38 AM, adammontville wrote:

> I agree that privacy needs to be covered.
> 
> Still, when we talk about /identity/ or /identification/ in this 
> working group, we're talking about something different than PII data. 
> As such, there's this other issue for the information model 
> sacmwg/draft-ietf-sacm-information-model#21 
> https://github.com/sacmwg/draft-ietf-sacm-information-model/issues/21, 
> which is seeking to get feedback on what a useful term other than 
> identity might be. The present candidate seems to be /designate/. So, 
> instead of "identify an endpoint" we would "designate an endpoint" or 
> "collect AVPs from the designated set of endpoints".
> 
> I also wouldn't go so far as to say that we're performing pervasive 
> monitoring in the sense that mainstream media understands the term. 
> Our scope has always been single-enterprise, and it remains that way.
> 
> Again, privacy is important, but I don't think we're talking about PII 
> as much as might be implied by our choice of terms.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/sacmwg/draft-ietf-sacm-requirements/issues/55#issuecomment-128680469.
> 
> ---
> 
> sacm mailing list
> sacm@ietf.org
> https://www.ietf.org/mailman/listinfo/sacm

## 

---

Ron Colvin CISSP, CAP, CEH
Certified Security Analyst
NASA - Goddard Space Flight Center
ron.colvin@nasa.gov
Direct phone 301-286-2451
NASA Jabber (rdcolvin@im.nasa.gov) AIM rcolvin13
NASA LCS (ronald.d.colvin@nasa.gov)

---

**Comment by sacm** [comment]
Hi,

When an enterprise network is breached by an outside attacker (using "if"
no longer seems appropriate) or is compromised by an inside attacker, the
SACM components that have datastores of devices and associated identity
info as well as (often) associated user identities are high-value targets of
attacks for bulk theft of PII.

By its fundamental nature, SACM increases the threat of exposure of PII
and therefore should address anonymization of individual device identity
info and strong controls on the dissemination of that info to subscribers.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
Winter  579 Park Place  Saline, MI  48176  734-944-0094
Summer  PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by sacm** [comment]
Hello,

This is a good discussion and it seems that it is getting to the right
set of points, that we do need to worry about index data and ways to
correlate information back to systems and possibly to users of those
systems or whose data crosses those systems.

Jim is right on the PM angle, but you can phrase this lots of ways.
In terms of privacy, we worry about indexes, anything considered
sensitive that requires confidentiality related to privacy, and PII.
There are lots of ways to handle this and that will be up to the WG to
decide how to provide such guidance.  We do have materials to help you
from the view of developing protocols.

Here are some links from a slide I've been using in presentations
(please do read the RFC listed, it's very helpful):
IETF Privacy Considerations for Internet protocols
  –https://datatracker.ietf.org/doc/rfc6973/
  –Data protection
     ▪Object level encryption
     ▪Determining when data is not necessary
     ▪Obscuring data or generalizing when possible
     ▪Protections on sensitive data and indexes to that data
  –Push for encrypted traffic
IAB Statement on Internet Confidentiality
  –https://www.iab.org/2014/11/14/iab-statement-on-internet-confidentiality/

Pervasive Monitoring is an Attack
  –RFC7258/BCP188 published after major IETF LC debate – sets the
basis for further actions
  –https://www.rfc-editor.org/rfc/rfc7258.txt

In case you missed the tech plenary for IETF88 and you prefer video
over reading (or in addition), this was a great plenary that gives
background into these considerations for the IETF:
http://www.ietf.org/live/ietf88/text.html

Unofficial stuff:
Blog from Snowden Q&A in Prague:
https://www.mnot.net/blog/2015/07/20/snowden_meets_the_ietf

If you missed the Snowden Q&A on Sunday of Prague, here is a link:
https://www.youtube.com/watch?feature=youtu.be&v=0NvsUXBCeVA&app=desktop

We are also working with the IEEE on their privacy work.  This
includes work to ensure MAC addresses can't be used to identify hosts
(and thus users of the hosts).

Thanks,
Kathleen

On Fri, Aug 7, 2015 at 10:51 AM, Ira McDonald blueroofmusic@gmail.com wrote:

> Hi,
> 
> When an enterprise network is breached by an outside attacker (using "if"
> no longer seems appropriate) or is compromised by an inside attacker, the
> SACM components that have datastores of devices and associated identity
> info as well as (often) associated user identities are high-value targets of
> attacks for bulk theft of PII.
> 
> By its fundamental nature, SACM increases the threat of exposure of PII
> and therefore should address anonymization of individual device identity
> info and strong controls on the dissemination of that info to subscribers.
> 
> Cheers,
> - Ira
> 
> Ira McDonald (Musician / Software Architect)
> Co-Chair - TCG Trusted Mobility Solutions WG
> Chair - Linux Foundation Open Printing WG
> Secretary - IEEE-ISTO Printer Working Group
> Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
> IETF Designated Expert - IPP & Printer MIB
> Blue Roof Music / High North Inc
> http://sites.google.com/site/blueroofmusic
> http://sites.google.com/site/highnorthinc
> mailto: blueroofmusic@gmail.com
> Winter  579 Park Place  Saline, MI  48176  734-944-0094
> Summer  PO Box 221  Grand Marais, MI 49839  906-494-2434
> 
> On Fri, Aug 7, 2015 at 10:01 AM, Ron Colvin Ron.Colvin@nasa.gov wrote:
> 
> > My understanding on PII is that as soon as I associate a person with an
> > email address, phone number or physical address I have PII that I need to
> > protect. If we associate a user id, account or user provisioned PKI with a
> > device including possibly a MAC address we probably have the same concerns.
> > 
> > I think in many cases user certificates are used for device authentication
> > and I thought that was an attribute that was highly desirable.
> > 
> > On 8/7/15 7:38 AM, adammontville wrote:
> > 
> > I agree that privacy needs to be covered.
> > 
> > Still, when we talk about identity or identification in this working
> > group, we're talking about something different than PII data. As such,
> > there's this other issue for the information model
> > sacmwg/draft-ietf-sacm-information-model#21, which is seeking to get
> > feedback on what a useful term other than identity might be. The present
> > candidate seems to be designate. So, instead of "identify an endpoint" we
> > would "designate an endpoint" or "collect AVPs from the designated set of
> > endpoints".
> > 
> > I also wouldn't go so far as to say that we're performing pervasive
> > monitoring in the sense that mainstream media understands the term. Our
> > scope has always been single-enterprise, and it remains that way.
> > 
> > Again, privacy is important, but I don't think we're talking about PII as
> > much as might be implied by our choice of terms.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> > 
> > ---
> > 
> > sacm mailing list
> > sacm@ietf.org
> > https://www.ietf.org/mailman/listinfo/sacm
> > 
> > ## 
> > 
> > ---
> > 
> > Ron Colvin CISSP, CAP, CEH
> > Certified Security Analyst
> > NASA - Goddard Space Flight Center
> > ron.colvin@nasa.gov
> > Direct phone 301-286-2451
> > NASA Jabber (rdcolvin@im.nasa.gov) AIM rcolvin13
> > NASA LCS (ronald.d.colvin@nasa.gov)
> > 
> > ---
> > 
> > ---
> > 
> > sacm mailing list
> > sacm@ietf.org
> > https://www.ietf.org/mailman/listinfo/sacm
> 
> ---
> 
> sacm mailing list
> sacm@ietf.org
> https://www.ietf.org/mailman/listinfo/sacm

## 

Best regards,
Kathleen

**Comment by sacm** [comment]
Hi all,

I completely agree that our privacy considerations need to explicitly call out these issues and provide guidance that this information needs to be protected as any other PII would be protected.  

Rather than SACM getting into the details of what comprises that protection, I'd rather see us refer out to the work that's already been done by many other groups in characterizing that protection - such the two Kathleen mentions here, RFC6973 (great resource, thank you!) and the IAB statement, and possibly resources from other standards bodies such as the NIST guide to protecting PII (http://csrc.nist.gov/publications/nistpubs/800-122/sp800-122.pdf - see http://csrc.nist.gov/publications/nistbul/april-2010_guide-protecting-pii.pdf for a summary).  No point in re-inventing the wheel when we can point to someone else's wheel instead. :)

Regards,
Lisa

-----Original Message-----

**Comment by sacm** [comment]
Good discussion and just a note in an effort to help make this easier
for you all.  If you call out any data used as an index or sensitive
data, then offer options for protection (could be leaving that data
out or using role names instead of specific users for instance) and
discuss the need for confidentiality and privacy protections, that
should be enough for the draft.  There may be other considerations
outside of data model elements, so reading the referenced RFCs would
be good as the IETF's use of the word privacy is broader than that of
enterprises.  For SACM, a service provider environment might also be
considered in scope as an "enterprise".

I'll look for this section when doing an AD review and should catch
most things that would come up in the IESG review to help correct them
before it goes on for the following review phase as well.

Thanks,
Kathleen

On Fri, Aug 7, 2015 at 12:14 PM, Lisa Lorenzin
llorenzin@pulsesecure.net wrote:

> Hi all,
> 
> I completely agree that our privacy considerations need to explicitly call out these issues and provide guidance that this information needs to be protected as any other PII would be protected.
> 
> Rather than SACM getting into the details of what comprises that protection, I'd rather see us refer out to the work that's already been done by many other groups in characterizing that protection - such the two Kathleen mentions here, RFC6973 (great resource, thank you!) and the IAB statement, and possibly resources from other standards bodies such as the NIST guide to protecting PII (http://csrc.nist.gov/publications/nistpubs/800-122/sp800-122.pdf - see http://csrc.nist.gov/publications/nistbul/april-2010_guide-protecting-pii.pdf for a summary).  No point in re-inventing the wheel when we can point to someone else's wheel instead. :)
> 
> Regards,
> Lisa
> 
> -----Original Message-----
> From: sacm [mailto:sacm-bounces@ietf.org] On Behalf Of Kathleen Moriarty
> Sent: Friday, August 07, 2015 11:35 AM
> To: Ira McDonald blueroofmusic@gmail.com
> Cc: sacmwg/draft-ietf-sacm-requirements draft-ietf-sacm-requirements@noreply.github.com; sacmwg/draft-ietf-sacm-requirements reply@reply.github.com; sacm sacm@ietf.org; Ron.Colvin@nasa.gov
> Subject: Re: [sacm] [draft-ietf-sacm-requirements] Do we need a privacy section (#55)
> 
> Hello,
> 
> This is a good discussion and it seems that it is getting to the right set of points, that we do need to worry about index data and ways to correlate information back to systems and possibly to users of those systems or whose data crosses those systems.
> 
> Jim is right on the PM angle, but you can phrase this lots of ways.
> In terms of privacy, we worry about indexes, anything considered sensitive that requires confidentiality related to privacy, and PII.
> There are lots of ways to handle this and that will be up to the WG to decide how to provide such guidance.  We do have materials to help you from the view of developing protocols.
> 
> Here are some links from a slide I've been using in presentations (please do read the RFC listed, it's very helpful):
> ŸIETF Privacy Considerations for Internet protocols
>   –https://datatracker.ietf.org/doc/rfc6973/
>   –Data protection
>      ▪Object level encryption
>      ▪Determining when data is not necessary
>      ▪Obscuring data or generalizing when possible
>      ▪Protections on sensitive data and indexes to that data
>   –Push for encrypted traffic
> ŸIAB Statement on Internet Confidentiality
>   –https://www.iab.org/2014/11/14/iab-statement-on-internet-confidentiality/
> 
> Pervasive Monitoring is an Attack
>   –RFC7258/BCP188 published after major IETF LC debate – sets the basis for further actions
>   –https://www.rfc-editor.org/rfc/rfc7258.txt
> 
> In case you missed the tech plenary for IETF88 and you prefer video over reading (or in addition), this was a great plenary that gives background into these considerations for the IETF:
> http://www.ietf.org/live/ietf88/text.html
> 
> Unofficial stuff:
> Blog from Snowden Q&A in Prague:
> https://www.mnot.net/blog/2015/07/20/snowden_meets_the_ietf
> 
> If you missed the Snowden Q&A on Sunday of Prague, here is a link:
> https://www.youtube.com/watch?feature=youtu.be&v=0NvsUXBCeVA&app=desktop
> 
> We are also working with the IEEE on their privacy work.  This includes work to ensure MAC addresses can't be used to identify hosts (and thus users of the hosts).
> 
> Thanks,
> Kathleen
> 
> On Fri, Aug 7, 2015 at 10:51 AM, Ira McDonald blueroofmusic@gmail.com wrote:
> 
> > Hi,
> > 
> > When an enterprise network is breached by an outside attacker (using "if"
> > no longer seems appropriate) or is compromised by an inside attacker,
> > the SACM components that have datastores of devices and associated
> > identity info as well as (often) associated user identities are
> > high-value targets of attacks for bulk theft of PII.
> > 
> > By its fundamental nature, SACM increases the threat of exposure of
> > PII and therefore should address anonymization of individual device
> > identity info and strong controls on the dissemination of that info to subscribers.
> > 
> > Cheers,
> > - Ira
> > 
> > Ira McDonald (Musician / Software Architect) Co-Chair - TCG Trusted
> > Mobility Solutions WG Chair - Linux Foundation Open Printing WG
> > Secretary - IEEE-ISTO Printer Working Group Co-Chair - IEEE-ISTO PWG
> > Internet Printing Protocol WG IETF Designated Expert - IPP & Printer
> > MIB Blue Roof Music / High North Inc
> > http://sites.google.com/site/blueroofmusic
> > http://sites.google.com/site/highnorthinc
> > mailto: blueroofmusic@gmail.com
> > Winter  579 Park Place  Saline, MI  48176  734-944-0094 Summer  PO Box
> > 221  Grand Marais, MI 49839  906-494-2434
> > 
> > On Fri, Aug 7, 2015 at 10:01 AM, Ron Colvin Ron.Colvin@nasa.gov wrote:
> > 
> > > My understanding on PII is that as soon as I associate a person with
> > > an email address, phone number or physical address I have PII that I
> > > need to protect. If we associate a user id, account or user
> > > provisioned PKI with a device including possibly a MAC address we probably have the same concerns.
> > > 
> > > I think in many cases user certificates are used for device
> > > authentication and I thought that was an attribute that was highly desirable.
> > > 
> > > On 8/7/15 7:38 AM, adammontville wrote:
> > > 
> > > I agree that privacy needs to be covered.
> > > 
> > > Still, when we talk about identity or identification in this working
> > > group, we're talking about something different than PII data. As
> > > such, there's this other issue for the information model
> > > sacmwg/draft-ietf-sacm-information-model#21, which is seeking to get
> > > feedback on what a useful term other than identity might be. The
> > > present candidate seems to be designate. So, instead of "identify an
> > > endpoint" we would "designate an endpoint" or "collect AVPs from the
> > > designated set of endpoints".
> > > 
> > > I also wouldn't go so far as to say that we're performing pervasive
> > > monitoring in the sense that mainstream media understands the term.
> > > Our scope has always been single-enterprise, and it remains that way.
> > > 
> > > Again, privacy is important, but I don't think we're talking about
> > > PII as much as might be implied by our choice of terms.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > > 
> > > ---
> > > 
> > > sacm mailing list
> > > sacm@ietf.org
> > > https://www.ietf.org/mailman/listinfo/sacm
> > > 
> > > ## 
> > > 
> > > ---
> > > 
> > > Ron Colvin CISSP, CAP, CEH
> > > Certified Security Analyst
> > > NASA - Goddard Space Flight Center
> > > ron.colvin@nasa.gov
> > > Direct phone 301-286-2451
> > > NASA Jabber (rdcolvin@im.nasa.gov) AIM rcolvin13 NASA LCS
> > > (ronald.d.colvin@nasa.gov)
> > > 
> > > ---
> > > 
> > > ---
> > > 
> > > sacm mailing list
> > > sacm@ietf.org
> > > https://www.ietf.org/mailman/listinfo/sacm
> > 
> > ---
> > 
> > sacm mailing list
> > sacm@ietf.org
> > https://www.ietf.org/mailman/listinfo/sacm
> 
> ## 
> 
> Best regards,
> Kathleen
> 
> ---
> 
> sacm mailing list
> sacm@ietf.org
> https://www.ietf.org/mailman/listinfo/sacm

## 

Best regards,
Kathleen

**Comment by jimsch** [comment]
Adam,

While it is true that we are focused on the single enterprise systems.  I will be shocked if there are not third parties that will offer to do the monitoring on my behalf.  This means that they are going to have to ability to look not only at the systems and users in my enterprise, but potentially compare them against systems and users in other enterprises.  

Also, although we are looking at single enterprise systems, my ISP is a single enterprise and can do the monitoring against me and anybody in my enterprise.

**Comment by sacm** [comment]
I had another thought after I sent my last message that should be helpful as you develop language prior to IETF last call.  Make sure the privacy considerations are not country specific.  The IETF references will help with that.  If you use NIST's, you'll also need to look at guidance from other countries, and that can get tricky.

Thanks,
Kathleen

**Comment by llorenzin** [comment]
In Prague, Lucy Lynch offered to review the drafts and provide comments on privacy
Dan will send her a reminder and solicit feedback from her.
Authors are soliciting a volunteer to write a privacy considerations section.  (I do not have the experience to do so, and my impression is that Nancy does not have the bandwidth.)
Kathleen offers to assist - can suggest text if it's not there by the time we get to AD review.  Will let us know if it's lacking or will have problems that will hold it up in IESG.
Henk - comments on-list about endpoint identifying attributes will have impact on this section.

**Comment by ncamwing** [comment]
Wow, this has been a good discussion.  Given that this is a requirements draft, I'm not sure how much information we need to provide (RFC 6973 is a good base to recommend).  So here is a proposed new section to address some of this (please comment so that I can place into the next version):

5.2.  Privacy Considerations
   SACM information may contain sensitive information about the target
   endpoint as well as revealing identity information of the producer or
   consumer of such information.  Similarly, as part of the SACM
   discovery mechanism, the advertised capabilities (and roles, e.g.
   SACM components enabled) by the endpoint may be construed as private
   information.  There may be applications as well as business and
   regulatory practicess that require that aspects of such information
   be hidden from any parties that do not need to know it.

   Data confidentiality can provide some level of privacy but may fall
   short where unecessary data is still transmitted.  In those cases,
   filtering requirements at the data model MUST be applied to ensure
   that such data is not disclosed.  [RFC6973] provides guidelines for
   which SACM protocols and information and data models should follow.

Comments? - Nancy

**Comment by dromasca** [comment]
Hi,

This looks good, but I have a clarification question. What does ‘filtering requirements at the data model MUST be applied’ mean? We already have OP-005 which states that ‘The query operation MUST support filtering’. Why do we need another capitalized MUST? Or do we have something else in mind?

Thanks and Regards,

Dan

**Comment by ncamwing** [comment]
Hi Dan,

You are right, I thought I needed the MUST to be consistant with both OP-005 and G-011, if it is redundant then I can reduce it to just "must".  

```
Nancy.
```
