### ISSUE TITLE
Captialization consistency

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#58]
Version -09

The document is not consistent if the character following the pithy title is capitalized.  A pass needs to be made to fix this.

**Comment by ncamwing** [comment]
Hi Jim,

I only found 1 straggler in IM-001....if there are others please let me know so I can fold it into the -10 draft.

Thanks, Nancy

**Comment by jimsch** [comment]
Fixed in Pull request #62
