### ISSUE TITLE
DM-006 Provider Identification

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#59]
Version -09

I am not sure what this statement is actually trying to say.  I first read it as referring to a Data Origin source, but then realized that this could refer to a provider in the architecture sense.  This should probably be clarified.

**Comment by ncamwing** [comment]
Hi Jim,
The intent is to have the endpoint acting an instance of a SACM Provider's identity be specified.
Would the following be more clear (as a replacement to the 1st sentence):
The data model MUST include the ability to provide the identity of the SACM Provider.

Thanks, Nancy

**Comment by jimsch** [comment]
That does not seem to say the same thing as the current sentence.   I think what you want to say is closer to:

The interfaces and actions in the data model MUST include the ability to identify data published by a specific provider.

I used published because I don't know if there is a better SACM verb.  What I mean by it is "data collected, processed or assessed".  That is data that originated with that provider as oppose to data which it received from elsewhere and relayed on.

**Comment by ncamwing** [comment]
Hi Jim,

I think it is the distinction is that when the data is provided, in that encapsulation there must be a means to specify the provider of that data.....that is what I was striving for.....I interpret the "identify data published by a specific provider" as potentially being a separate interface as well?

```
Nancy.
```

**Comment by jimsch** [comment]
Getting back into the flow of things again.

This seems to me to be better stated as an operation requirement than as a data model requirement.   The query would say - only get the data from provider X.  However it is not clear that I would model this as part of the data when I am doing processing on it.  I would not necessary expect to keep this as part of my internal data structures.

Data source is already provided as DM-0012 so that would not need to be duplicated here.

I would suggest 
OP-XXXX  Provider Restriction:  Request operations MUST include the ability to restrict the data to be provided by a specific provider or a provider with specific characteristics.  Response operations MUST include the ability to identify the provider that supplied the response.  For example, a SACM consumer should be able to request that all of the data come from a specific provider by identity (e.g. Provider A) or from a provider that is in a specific location (e.g. in the Boston office).

**Comment by ncamwing** [comment]
Hi Jim,
I have the suggested text now in the merged branch and will fold it into rev -12
