### ISSUE TITLE
Section 2 - "Report the results..."

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#6]
Version -04
1.  Suggested task name:  (not in terminology document - should it be there) "Report Results:"
2.  Suggest added some additional text to this bullet.
   Report the results of the evaluation for use by other components.  Examples of use of a report would be additional evaluation, network enforcement, vulnerability detection and license management.

**Comment by ncamwing** [comment]
Hi Jim,
#1: seems redundant to add the task name?  But I've added it as its more of a nit :-P
#2: done in -05

**Comment by jimsch** [comment]
Looks fine to me.
