### ISSUE TITLE
Should the requirements draft define the scope of the working group?

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-requirements#65]
Suggest the following text:

This document defines the set of requirements for the Secure Automation and Continuous Monitoring (SACM) architecture, data model and transport protocols. The requirements are based on the agreed upon use cases.

**Comment by ncamwing** [comment]
Not sure it is a hard requirement, there is some text in the Introduction (last paragraph):
This document focuses on describing the requirements for facilitating the exchange of posture assessment information in the enterprise, in particular, for the use cases as exemplified in
   [I-D.ietf-sacm-use-cases].  Also, this document uses terminology defined in [I-D.ietf-sacm-terminology]. 

Which is very close to what you suggested....is that sufficient or do you want further edits?

**Comment by adammontville** [comment]
If no one else has opined, existing text is sufficient.
