### ISSUE TITLE
Requirements terminology reconciliation with Terminology draft

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-requirements#67]
Section 2 of the requirements draft defines some terms.  Have these been reconciled with our terminology draft?  Probably a question for @henkbirkholz as well as @ncamwing

**Comment by ncamwing** [comment]
Henk and I will need to go through them....we did try to reconcile them prior to -11 but likely, it is a continuous process

**Comment by adammontville** [comment]
Ok. This doesn't seem like something that should take too long.  Maybe we can get through them within the next week.

**Comment by henkbirkholz** [comment]
First update of the terminology draft addressing this issue can be found in the corresponding git, including examples of "SACM Task" that are highlighted in the req draft. Names of examples do not align smoothly with current definitions and copied examples might need some work, in general.

**Comment by llorenzin** [comment]
This seems like an open issue for the terminology draft rather than the requirements draft.  Do you agree?  If so, can we close it here and open one there?

**Comment by sacm** [comment]
Hi

The terminology draft was started to contain terminology used across multiple documents so you would need to look at whether other documents had dependencies on the common terminology before changing the terminology draft to match the requirements draft. 

David Harrington
Dbharrington@comcast.net
603-828-1401

**Comment by llorenzin** [comment]
VI - consensus to close this issue on the requirements draft and open a corresponding issue in the terminology draft
