### ISSUE TITLE
Is an endpoint not an asset itself?

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-requirements#68]
The definition for "Asset Classification" contains: "Map the assets on the target endpoints to asset classes".  Is the endpoint not a subject for classification itself?

**Comment by ncamwing** [comment]
Yes, it is....though an endpoint could be identified by its assets as well.  How would you suggest to clarify?

**Comment by adammontville** [comment]
How about: "Map the target endpoint and/or the assets on the target endpoint to asset classes."  The way it reads currently may lead someone to infer that an endpoint cannot be classified as an asset.

**Comment by ncamwing** [comment]
OK, will update on rev -12
