### ISSUE TITLE
Clarify push/pull and solicited/unsolicited in GM-011, IM-002, and DM-015 

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-requirements#69]
G-011 states that there are three methods of data access to support: "the standard Pull model as well as solicited and unsolicited Push models."  This wording creates "solicited push" and "unsolicited push".  Later, IM-002 states, "no aspect of the information model should be dependent upon or assume a push (unsolicited) or pull (solicited) model of publication.  This wording indicates that "unsolicited" is a synonym for "push" and that "solicited" is a synonym for "pull".  Then even later, DM-015 states, "the data model MUST enable a provider to publish data either solicited (in response to a request from a consumer) or unsolicited (as new data is generated, without a request required)".  This wording suggests the same synonyms as expressed in IM-002.

Which is the correct perspective?

**Comment by ncamwing** [comment]
Hi Adam,
You are right, there are inconsistencies.  The clarification in that a "push" could come 'solicited' vs. 'unsolicited' came from the notion of a registered "update" request (in the case of 'solicited') vs. 'unsolicited' which could be a broadcast by the publisher.  That said, I will remove "solicited" and "unsolicited" from the IM-002 description.  
Though I think the DM-015 still seems correct as a solicitation can be a request to provide the data now vs. update.

**Comment by adammontville** [comment]
Fair.

**Comment by adammontville** [comment]
Are we planning to close this?

**Comment by adammontville** [comment]
Or am I supposed to close this because I submitted the issue?
