### ISSUE TITLE
Requirement G-001 - Solution Extensibility

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#7]
Version -04
1.  In the first sentence s/data models/information models/.   While it is good that the data models would be extensible as well, I don't know that is is clear that SACM will be defining data models and it is clear it is doing some type of information model.
2.  I can see a must for future extensions,  I don't know that I see a must for non-standard extensions.  I am sure I could dream up non-standard extensions that it will not be very extensible for.  
3.  s/be extensible to/be designed to/
4.  bullet 1 - I don't know what this means.  Do you mean that version 1 transports must be able to transport new (v2) operations or that a v2 transport must be able to transport all v1 operations?  I am assuming you mean to say the former.   "SACM defined transport protocols MUST have an extensibility to allow them to transport operations that are defined in the future."
5. bullet 2 -  I don't understand the concept of specific paths to follow.  What is meant here?
6. bullet 2 - s/event, as well as on a continuous basis/event or on a continuous basis/
7.  bullet 2 - s$and/or$or$
8. bullet 3 - s/in a backward compatible fashion//  - just say that new stuff needs to be able to be added.

**Comment by ncamwing** [comment]
Hi Jim,

#1: One info model and at least one data model will be defined.  Proposed data models need to support the mandatory elements specified in the information model

#2: fair point, I will remove "non-standard"....

#3: done in -05
#4:the bullets got mangled somehow, the first bullet is really more about the information model defining operations and allow for new ones to be defined in a backwards compatible means.
#5:as I'm re-reading it, it was an old comment that I incorporated text to and am now wondering whether it should be in scope or not.  The reference of "paths" I believe was about wanting to follow the originating source of the data.  This bullet doesn't even belong in the "general" requirements and now I'm not sure it even belongs as part of the data model requirements? Another one to discuss w/the group
#6: done (though will move or remove after discussion)
#7: done in -05
#8: done in -05

**Comment by llorenzin** [comment]
#2 Please do not remove "non-standard extensions".  The point there is that SACM is defining a set of standard data models, protocols, and transports - but we want the SACM ecosystem to not be constrained to _only_ use those data models, protocols, and transports.  So, for example, if we define a data model for endpoint posture data, and someone else defines a data model for endpoint behavior data, that is a non-standard data model - but if SACM is created with the appropriate extensibility, you should still be able to carry that data model over the standard transport.  Likewise, we will define a standard transport, but ideally that won't be the _only_ transport you can use. That's what "non-standard" means to me in this context.

**Comment by jimsch** [comment]
Can you give an example of something that would not fit into the concept of "future extensions" that would fit into the concept of "non-standard extensions"?

**Comment by llorenzin** [comment]
Consensus to leave as exists in -07.

**Comment by jimsch** [comment]
Not happy with the result but it is no longer worth fighting.
