### ISSUE TITLE
T-005 Transport Reliability question

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-requirements#76]
Will SACM communications _necessarily_ need to be sent over reliable transports?  Some less critical or very bandwidth-constrained environments might benefit from transports that typically suffice but which do not guarantee reliability.  The answer may well be yes.

**Comment by jimsch** [comment]
Are you talking about the network transport or the SACM transport as being reliable?  I would expect that the network transport could be unreliable, i.e. it would be UDP as an option.  However, I would expect that the SACM transport running on top of UDP would have provisions to make the unreliable transport be a reliable one - such as conformations and re-transmits.

**Comment by ncamwing** [comment]
Agree with Jim....if SACM chooses a non-reliable based nw transport, then SACM has to provision reliability

**Comment by llorenzin** [comment]
I propose that we update the existing requirement: 
T-005  Transport Reliability: SACM transport protocols MUST provide
    reliable delivery of data.  This includes the ability to perform
    fragmentation and reassembly, and to detect replays.
to:
T-005  Transport Reliability: SACM transport protocols MUST provide
    reliable delivery of data.  This includes the ability to perform
    fragmentation and reassembly, and to detect replays. The SACM transport may take advantage of reliability features in the network transport; however, the network transport may be unreliable (e.g. UDP), in which case the SACM transport running over the unreliable network transport is responsible for ensuring reliability (i.e. by provisions such as confirmations and re-transmits).

**Comment by jimsch** [comment]
Wordy but works

**Comment by adammontville** [comment]
Agree

**Comment by llorenzin** [comment]
Done in -13
