### ISSUE TITLE
Security Considerations - proposed text change

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-requirements#77]
Given the actual scope of our charter, I'm proposing the following text to replace the first sentence in the last paragraph of the Security Considerations section (adding "workflow orchestration"):

"SACM’s charter focuses on the workflow orchestration and sharing of posture information for improving efficacy of security applications such as compliance, configuration, assurance and other threat and vulnerability reporting and remediation systems."

**Comment by ncamwing** [comment]
Updated in rev -12
