### ISSUE TITLE
first sentence in the Introduction section

### ISSUE THREAD

**Issue by dromasca** [sacmwg/draft-ietf-sacm-requirements#78]
The first sentence in the Introduction section reads: 

> Today's environment of rapidly-evolving security threats highlights
>    the need to automate the sharing of such information while protecting
>    user information as well as the systems that store, process, and
>    transmit this information.

As this is the very first sentence in the Introduction section, there is no previous content that hints what 'such information' is supposed to mean.

**Comment by ncamwing** [comment]
Hi Dan,
The intent was to reference the "threat information"....but given that SACM is focused on "posture information" (that leads to the potential of a threat) it does need to be revised. 
I will update as follows:
Today's environment of rapidly-evolving security threats highlights the need to automate the sharing of security information (such as posture information) while protecting user information as well as the systems that store,  process, and transmit this information.
