### ISSUE TITLE
requirements related to IM

### ISSUE THREAD

**Issue by dromasca** [sacmwg/draft-ietf-sacm-requirements#79]
In section 2. Requirements, first paragraph: 

>  These requirements express characteristics or features that a
>    candidate protocol or data model must be capable of offering to
>    ensure security and interoperability.

I believe that information model should also be mentioned here, as the document has a dedicated separate section for the information model. Suggested changed text: 

>  These requirements express characteristics or features that a
>    candidate protocol, information model or data model must be 
>    capable of offering to ensure security and interoperability.

**Comment by athiasjerome** [comment]
+1

**Comment by ncamwing** [comment]
Updated in rev -12
