### ISSUE TITLE
G-002 Interoperability

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#8]
Version -04
1.  Are we specifying data models?  Need to include information models instead?
2.  If this is a requirement on SACM defined items, then it can be removed.  If this is a requirement on other people, then it probably out of scope and can be removed.  If you don't do this then you don't have a successful document.

**Comment by ncamwing** [comment]
Hi Jim,

#1: one Information Model that data models need to adhere to....so SACM should have at least one data model defined.

#2: I will put it to the group to discuss....it has been raised before but someone felt it needed to be there ergo its presence persisting in the draft :-)

   Nancy.

**Comment by llorenzin** [comment]
This is a requirement for SACM defined items, and i don't think it can be removed any more than the requirements for extensibility, scalability, etc. could be removed. If we remove this requirement, then arguably we could define an information model with no minimum attribute set, such that all attributes are implementation-specific and must be individually agreed-upon between any consumer/provider pair, and still meet the requirements.  I don't think we want that!

**Comment by jimsch** [comment]
I think that it is a harmless requirement to retain.

**Comment by jimsch** [comment]
See previous note.
