### ISSUE TITLE
G-001/1: what interfaces?

### ISSUE THREAD

**Issue by dromasca** [sacmwg/draft-ietf-sacm-requirements#82]
In G-001: 

> The information model and interfaces MUST support the ability to
>         add new operations while maintaining backwards compatibility.

It is not clear what 'interfaces' are meant here.

**Comment by jimsch** [comment]
Interfaces is more defined in G-012.

**Comment by dromasca** [comment]
G-012 refers to device interfaces.

Here the text is: ‘The information model and interfaces MUST support …’ – do we mean here ‘device interfaces’? It does not make too much sense to me in an extensibility requirement. In any case, it must be specified – that what exactly the question.

Regards,

Dan

**Comment by ncamwing** [comment]
Hi,
By interfaces I meant programming interfaces which can be a protocol as well; that is, the means by which information is being communicated.  So from that standpoint, G-012 is the expansion to "interfaces" in G-001.

I can update it with a forward reference, so instead of "interfaces" it is "device interfaces (see G-012)"....OK?

**Comment by dromasca** [comment]
OK with me.

Thanks and Regards,

Dan

**Comment by henkbirkholz** [comment]
Maybe the name of G-012 is also a little bit confusing? It might be just me, but "G-012 Device Interface" does not sound like a programming interface or protocol.

The architecture draft states that SACM components have SACM interfaces for communication between SACM components.

SACM (component) interfaces?

**Comment by dromasca** [comment]
Yes. Clarifying the we mean programmatic interfaces would help, as ‘device interfaces’ has a different meaning for many people.

Regards,

Dan

**Comment by llorenzin** [comment]
I like Henk's proposal of SACM Component Interfaces. Any objections?

**Comment by llorenzin** [comment]
Fixed in -12 (G-001) and -13 (G-012)
