### ISSUE TITLE
drop G-002

### ISSUE THREAD

**Issue by dromasca** [sacmwg/draft-ietf-sacm-requirements#83]
Issue G-002 seems to me content free. The scope of any standard including SACM is to ensure interoperability. The text of G-002 is synonymous with 'The SACM specifications MUST be well written'. This is unnecessary IMO and I suggest to drop this requirement.

**Comment by ncamwing** [comment]
I think this issue was raised before, but someone objected to its removal ergo its persistence in the draft.

How do we make sure we have consensus on this?

Thanks, Nancy

**Comment by llorenzin** [comment]
This was raised before in https://github.com/sacmwg/draft-ietf-sacm-requirements/issues/8 and the decision then was to leave it in. I still feel it's needed, for the same reasons I provided in that issue.
