### ISSUE TITLE
G-003: Scalability

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#9]
Version -04
1.  It is not clear that all transports need to be scalable.  While some may need to be others do not have that requirement.   For example the transport from the endpoint to the location where it is going to publish it's assessment probably does not need to deal with any of these issues.  I.e. they could publish over UDP potentially
2.  Is SACM going to be publishing data models?
3.  s/SCAM must support/SACM needs to support/
4.  s/(record or datagram)//  The parenthetical does not help clarity.
5.  s/requiring or producing (or both)/requiring and/or producing/

After reading this goal,  I am not sure how I would correctly evaluate if a proposal does this successfully?  For example, should a transport also address potential congestion issues as well?  That is not called out but would be part of this goal if one is a transport person, however it would be totally skipped if one is a pure security person.

**Comment by ncamwing** [comment]
Hi Jim,

Perhaps this is a subjective goal so you are right that it's not black/white requirement to evaluate for transports.  Would you prefer I remove it?

As to #2: I think data models will be proposed and part of the SACM charter.

#3 - #5 updates will be made in -05

Thanks, nancy.

**Comment by llorenzin** [comment]
I'm strongly against removing the requirement for transports to be scalable.  Lack of scalability of the transport is one of the biggest limitations of IF-MAP; I would strongly prefer that we have a clear requirement to avoid that known pitfall for SACM.

**Comment by jimsch** [comment]
Referring back to the question I asked on section 2.6 - What do you think a transport is?  TCP/IP or something else?

**Comment by ncamwing** [comment]
I have not removed it and agree that we need requirement for network layer transports, but it sounds like we need some level of clarification?

**Comment by llorenzin** [comment]
Discussed at 6/29 virtual interim, done in -07
