### ISSUE TITLE
IM-003: text clarifications

### ISSUE THREAD

**Issue by dromasca** [sacmwg/draft-ietf-sacm-requirements#90]
In IM-003: 

>  SACM's information model MUST allow
>     support for different data models, data model versions, and
>     different versions of the operations (and network layer transport).

It is not clear what operations are meant here. Probably operations on data models. Also the term 'network layer transport' is not correct, as SACM transports can run on different layers. 

Possible edit: 

>  SACM's information model MUST allow
>     support for different data models, data model versions, and
>     different versions of the operations on data models and 
>     transport protocols.

**Comment by ncamwing** [comment]
Thanks for catching this Dan....will update per your suggested edit in revision -12
